plugins {
    id "java-library"
    id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${project.archives_base_name}-fabric"
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    implementation project(path: ":common")

    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    if (project.modmenu_version?.trim()) {
        if (project.modmenu_compile_only?.trim() == "true") {
            compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
        } else {
            implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
        }
    }
}

sourceSets {
    main {
        java {
            srcDir "../common/src/main/java"

            if (!project.modmenu_version?.trim()) {
                exclude "dev/fixyl/componentviewer/modmenu/**"
            }
        }
        resources {
            srcDir "../common/src/main/resources"
        }
    }
}

loom {
    runConfigs.configureEach {
        runDirectory = "../run"
        generateRunConfig = true
    }

    accessWidenerPath = file("src/main/resources/componentviewer-fabric.accesswidener")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

java {
    withSourcesJar()

    toolchain.languageVersion = JavaLanguageVersion.of(25)

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from "../LICENSE"
}

sourcesJar {
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }

    from "../LICENSE"
}
