# Gradle Properties
org.gradle.jvmargs=-Xmx2G
# Disabled parallel execution, because it caused build errors in VSCode.
# TODO: Fix/Rework this horrible build configuration at some point!
org.gradle.parallel=false

# Loom Properties
fabric.loom.multiProjectOptimisation=true

# Minecraft Version
minecraft_version=1.21.11

# Fabric Version
fabric_loader_version=0.18.4
fabric_loom_version=1.14-SNAPSHOT

# NeoForge Version (Optional)
neoforge_version=21.11.14-beta
moddev_version=2.0.134

# ParchmentMC Version (Optional)
parchment_minecraft_version=
parchment_mappings_version=

# Dependencies (ModMenu is Optional)
fabric_api_version=0.140.2+1.21.11
modmenu_version=17.0.0-beta.1

# Mod Properties
mod_id=componentviewer
mod_version=1.3.3+1.21.11

maven_group=dev.fixyl.componentviewer
archives_base_name=componentviewer
