# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Loom Properties
fabric.loom.multiProjectOptimisation=true

# Minecraft Version
minecraft_version=1.21.5

# Fabric Version
fabric_loader_version=0.17.2
fabric_loom_version=1.11-SNAPSHOT

# NeoForge Version (Optional)
neoforge_version=21.5.95
moddev_version=2.0.107

# ParchmentMC Version (Optional)
parchment_minecraft_version=1.21.5
parchment_mappings_version=2025.06.15

# Dependencies (ModMenu is Optional)
fabric_api_version=0.128.2+1.21.5
modmenu_version=14.0.0-rc.2

# Mod Properties
mod_id=componentviewer
mod_version=1.3.0+1.21.5

maven_group=dev.fixyl.componentviewer
archives_base_name=componentviewer
