# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Loom Properties
fabric.loom.multiProjectOptimisation=true

# Minecraft Version
minecraft_version=1.21.8

# Fabric Version
fabric_loader_version=0.17.2
fabric_loom_version=1.11-SNAPSHOT

# NeoForge Version (Optional)
neoforge_version=21.8.47
moddev_version=2.0.107

# ParchmentMC Version (Optional)
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14

# Dependencies (ModMenu is Optional)
fabric_api_version=0.133.4+1.21.8
modmenu_version=15.0.0

# Mod Properties
mod_id=componentviewer
mod_version=1.2.1+1.21.8

maven_group=dev.fixyl.componentviewer
archives_base_name=componentviewer
