plugins {
    id "java-library"
    id "net.fabricmc.fabric-loom-remap" version "${fabric_loom_version}"
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modCompileOnly "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
}

loom {
    runs {
        remove client
        remove server
    }

    accessWidenerPath = file("../fabric/src/main/resources/componentviewer-fabric.accesswidener")
}
