plugins {
    id "java-library"
    id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

repositories {
    maven {
        name = "ParchmentMC"
        url = "https://maven.parchmentmc.org/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    compileOnly "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
}

loom {
    runs {
        remove client
        remove server
    }

    accessWidenerPath = file("../fabric/src/main/resources/componentviewer-fabric.accesswidener")
}
